# Site settings
title: Research blog
email: jda@cs.berkeley.edu
description: Research blog about language and machine learning.
url: "http://blog.jacobandreas.net"

# Build settings
markdown: kramdown
highlighter: rouge
