# Site settings
title: blog
email: jda@cs.berkeley.edu
description: Notes on language, machine learning, etc.
url: "http://blog.jacobandreas.net"
permalink: /:title.html

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      comments: true
